name: python项目编译流程-开发环境

on:
  workflow_call:
    inputs:
      artifact_name:
        description: '制品名称'
        required: true
        type: string
      repository:
        description: '仓库地址'
        required: true
        type: string
      ref:
        description: '分支或标签'
        required: true
        type: string
      # 区分svn还是git
      repo_type:
        description: '仓库类型'
        default: 'git'
        required: false
        type: string
    # secrets:
    #   repo_token:
    #     description: '仓库认证令牌'
    #     required: false

# 组成工作流的jobs， 包含一个以上的job
jobs:
  build:
    name: 编译-python项目
    runs-on: ubuntu-latest
    # # 环境级别的配置变量必须指定, 无法使用变量动态配置-2023-12-08
    # environment: dev
    steps:
      - name: 打印变量
        run: |
          echo -e "repo_type=${{ inputs.repo_type }}\trepository=${{ inputs.repository }}\tref=${{ inputs.ref }}"
          echo -e "\033[33m_GITHUB_TOKEN=${{ secrets._GITHUB_TOKEN }}\033[0m"
        
      - name: 拉取代码 - svn仓库
        if: ${{ inputs.repo_type == 'svn' }}
        run: |
          svn --version --quiet &&  echo -e "\033[33m我拉取了svn仓库\033[0m" || echo -e "\033[31msvn命令不存在\033[0m"
        
      - name: 拉取代码 - git仓库
        if: ${{ inputs.repo_type == '' }}
        uses: actions/checkout@v4.1.1
        with: 
          repository: ${{ inputs.repository == '' && github.repository || inputs.repository }}
          ref: ${{ inputs.ref == '' && github.REF_NAME || inputs.ref }}
          token: ${{ secrets.repo_token == '' && github.token || secrets.repo_token }}
          
      - name: 配置编译环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'
          
      # - name: 安装依赖（测试代码需要）
      #   run: |
      #     python -c "import sys; print(sys.version)"
      #     python -m pip install --upgrade pip
      #     # pip install -r requirements.txt
      #     echo "hello" > $(date +"%Y_%m_%d_%H_%M_%S").txt
          
      - name: 执行编译
        run: |
          echo -e "job_id：$GITHUB_JOB  事件：$GITHUB_EVENT_NAME  操作人：$GITHUB_ACTOR - $GITHUB_ACTOR_ID"
          echo "workflow链接：$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/workflows/${GITHUB_WORKFLOW}.yml"
          echo -e "本次运行详细链接：$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo -e "配置变量-环境级别：${{ vars.ENV }}"
          pwd && ls -a
          echo -e "\033[36m我是编译脚本，执行完成\033[0m" 
          
      # - name: 测试代码
      #   run: python app.py
        
      - name: 打包压缩
        run: |
          rm -rf .git*
          tar -zcvf ${{ inputs.artifact_name }}.tgz *
          ls -l ${{ inputs.artifact_name }}.tgz && tar -tzvf ${{ inputs.artifact_name }}.tgz
          
      - name: 上传到artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_name }}.tgz
