name: 编译流程

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      # token:
      #   required: false
      #   type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 打印操作
      run: |
        echo -e "config-pat=>${{ inputs.config-path }}\ntoken=> ${{ secrets.token }}\nSSH_HOST=> ${{ secrets.SSH_HOST }}"
        echo "token=> ${{ secrets.token }}" > 1.txt && cat 1.txt
