name: ci_cd2

on:
  workflow_dispatch:

env:
  type: "flutter"

jobs:
  test1:
    name: 测试验证1
    runs-on: ubuntu-latest
    steps:
      - name: 打印变量
        run: |
          pwd
          echo -e "GH_TOKEN: ${{ secrets.GH_TOKEN }}"

      - uses: actions/cache@v3.3.2
        with:
          path: ./time.txt
          key: time-${{ runner.os }}-${{ GITHUB.WORKFLOW }}-${{ GITHUB.RUN_NUMBER }}
          restore-keys: time-

      - run: |
          [[ -f time.txt ]] && cat time.txt || echo "第一次运行没有生成time"
          echo $(date "+%F %T") > time.txt && echo "重新生成time"
          [[ -f time.txt ]] && cat time.txt || echo "查看重新生成的time"
          
      # - name: 拉代码
      #   uses: actions/checkout@v4.1.1
      #   with:
      #     repository: "deming-org/test-project"
      #     ref: main
      #     # token: ${{ secrets.GH_TOKEN }}
      # - name: 测试
      #   run: ls -al
      # - name: 执行脚本
      #   run: bash build.sh
      # - name: 输出
      #   run: |
      #     echo "开始打印"
      #     echo -e "\033[33m ${ipa_filename} \033[0m"
      #     echo -e "\033[33m $ipa_filename \033[0m"
      #     echo "结束打印"
          
      # - name: 判断1
      #   if: ${{ env.type == 'flutter' }}
      #   run: echo "flutter类型"
          
      # - name: 判断2
      #   if: ${{ env.type != 'flutter' }}
      #   run: echo "非flutter类型"

          
          
      #     ipa_filename="${{ github.WORKFLOW }}_1.0.0-build-1_$(date '+%F-%H-%M-%S').ipa"
      #     echo "ipa_filename=${ipa_filename}" >> "$GITHUB_ENV"
          
      #     wf_ipa_filename="ci_cd2_1.0.0-build-1_$(date '+%F-%H-%M-%S').ipa"
      #     echo "wf_ipa_filename=${wf_ipa_filename}" >> "$GITHUB_ENV"
          
      #     WF_IPA_FILENAME3="ci_cd2_1.0.0-build-1_`date '+%F-%H-%M-%S'`.ipa"
      #     echo "WF_IPA_FILENAME3=${WF_IPA_FILENAME3}" >> "$GITHUB_ENV"

      #     # GITHUB_、RUNNER_、CI_、WF_ 开头的变量不一定会生效
      #     WF_IPA_FILENAME="${{ github.WORKFLOW }}_1.0.0-build-1_$(date '+%F-%H-%M-%S').ipa"
      #     echo -e "设置后马上查看下：WF_IPA_FILENAME => $WF_IPA_FILENAME "
      #     echo "WF_IPA_FILENAME=${WF_IPA_FILENAME}" >> "$GITHUB_ENV"
      #     echo -e "设置环境变量后再查看下：WF_IPA_FILENAME => $WF_IPA_FILENAME "

      #     echo "WF_IPA_FILENAME=22.ipa" >> "$GITHUB_ENV"
      #     echo -e "设置后马上查看下：WF_IPA_FILENAME => $WF_IPA_FILENAME "
      #     echo "MY_VAR1=${WF_IPA_FILENAME}" >> "$GITHUB_ENV"
      #     echo -e "设置后马上查看下：MY_VAR1 => $MY_VAR1 "
          
      # - name: 输出作业内共享变量
      #   run: |
      #     echo "ipa_filename: $ipa_filename"
      #     echo "wf_ipa_filename: $wf_ipa_filename"
      #     echo "WF_IPA_FILENAME3: ${WF_IPA_FILENAME3}"
      #     echo "WF_IPA_FILENAME: ${WF_IPA_FILENAME}"
      #     echo "MY_VAR1: ${MY_VAR1}"
          
  # test2:
  #   name: 测试验证2
  #   # needs:
  #   #   - test1
  #   uses: ./.github/workflows/workflow-1.yml
  #   secrets: inherit
  #   with:
  #     config-path: ./ci_cd.yml
