name: ci_cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # 重置当前workflow的工作目录
  GITHUB_WORKSPACE: ${{ github.workspace}}/${{ github.workflow}}

jobs:
  test1:
    name: 测试验证1
    runs-on: ubuntu-latest
    steps:
      - name: 打印变量
        run: |
          pwd
          echo -e "GITHUB_WORKFLOW: $GITHUB_WORKFLOW \t GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
  test2:
    name: 测试验证2
    # needs:
    #   - test1
    uses: ./.github/workflows/workflow-1.yml
    secrets: inherit
    with:
      config-path: ./ci_cd.yml
