name: ci_cd2

on:
  workflow_dispatch:

jobs:
  test1:
    name: 测试验证1
    runs-on: ubuntu-latest
    steps:
      - name: 打印变量
        run: |
          pwd
          WF_IPA_FILENAME1="${{ github.WORKFLOW }}_1.0.0-build-1_$(date '+%F-%H-%M-%S').ipa"
          WF_IPA_FILENAME2="ci_cd2_1.0.0-build-1_$(date '+%F-%H-%M-%S').ipa"
          WF_IPA_FILENAME3="ci_cd2_1.0.0-build-1_`date '+%F-%H-%M-%S'`.ipa"
          WF_IPA_FILENAME4="ci_cd2_1.0.0-build-1_`date '+%F-%H-%M-%S'`.ipa"
          echo "MY_VARIABLE_NAME=${WF_IPA_FILENAME}" >> "$GITHUB_ENV"
          echo -e "GITHUB_WORKFLOW: $GITHUB_WORKFLOW \t GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
      - name: 输出作业内共享变量
        run: |
          echo "WF_IPA_FILENAME1: $WF_IPA_FILENAME1"
          echo "WF_IPA_FILENAME2: ${WF_IPA_FILENAME2}"
          echo "WF_IPA_FILENAME3: ${WF_IPA_FILENAME3}"
          echo "WF_IPA_FILENAME4: ${WF_IPA_FILENAME4}"
          
  # test2:
  #   name: 测试验证2
  #   # needs:
  #   #   - test1
  #   uses: ./.github/workflows/workflow-1.yml
  #   secrets: inherit
  #   with:
  #     config-path: ./ci_cd.yml
