name: diy-action
on: 
  workflow_dispatch:
    # inputs:
    #   ref:
    #     description: '分支或标签(正式使用的时候不要给默认值)'
    #     default: 'svn-python-demo-2.0.0'
    #     required: true
    #     type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: '测试使用'
    steps:
      - name: 拉取自定义的action
        uses: actions/checkout@v4.1.1
        
      - name: 测试拉代码action
        uses: ./.github/actions/action-checkout
        with:
          # 参数通过创建模板的api，动态生成
          repo_type: 'github'
          repository: 'deming-org/python-demo'
          ref: 'main'
          password: ${{ secrets.GH_TOKEN }}
          
      # - name: 测试编译action
      #   uses: ./.github/actions/action-build
      #   with:
      #     # language_type: 'python'
      #     # version: '3.9.13'
      #     # build_cmd: 'python -V && which python && which python3.9'
          
      #     # language_type: 'go'
      #     # version: '1.19'
      #     # build_cmd: 'go version && which go'

      #     language_type: 'node'
      #     version: '14.21'
      #     build_cmd: 'node -v && which node'
      
      # - name: 测试通知action
      #   uses: ./.github/actions/action-notification
      #   with:
      #     channel_type: 'feishu'
      #     send_addr: "${{ secrets.FS_ROBOT }}"
      #     content: '测试消息，通过自定义的action发送'
          
      - name: 验证
        run: |
          pwd && ls -lat
      # - name: 上面有步骤失败才执行
      #   if: ${{ failure() }}
      #   run: |
      #     pwd && ls -lt
      #     echo -e "\033[31m前面有步骤失败了\033[0m"
