name: IOSBuilder

on: 
  workflow_dispatch:

jobs:
  build:
    name: "编译作业"
    runs-on: macos-latest
    steps:
     - name: 拉取仓库代码
       uses: actions/checkout@v4.1.1
       with: 
          repository: "deming-org/ios-demo"
          ref: "main"

     - name: 创建证书配置目录
       run: |
         pwd && ls -at1
         mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles
         mkdir -pv ~/Library/MobileDevice/Certificates/
         echo -e "\033[33m验证一下\033[0m"
         ls -l ~/Library/MobileDevice/
       
     - name: base64解码p12证书字符
       id: certFileDecode
       uses: timheuer/base64-to-file@v1.2.4
       with:
        fileName: 'certificate.p12'
        encodedString: ${{ secrets.P12_BASE64 }}
     - name: 拷贝证书
       run: |
         mv ${{ steps.certFileDecode.outputs.filePath }} ~/Library/MobileDevice/Certificates/certificate.p12
         echo -e "\033[33m查看下目录内容\033[0m"
         ls -l ~/Library/MobileDevice/Certificates/
         
     - name: base64解码mobileprovision字符
       id: profFileDecode
       uses: timheuer/base64-to-file@v1.2.4
       with:
        fileName: 'decoded.mobileprovision'
        encodedString: ${{ secrets.MOBILEPROVISION_BASE64 }}
     - name: 拷贝mobileprovision
       run: |
         mv ${{ steps.profFileDecode.outputs.filePath }} ~/Library/MobileDevice/Provisioning\ Profiles/decoded.mobileprovision
         echo -e "\033[33m查看下目录内容\033[0m"
         ls -l ~/Library/MobileDevice/Provisioning\ Profiles/

     # - name: 安装必须的依赖
     #   uses: actions/setup-python@v2
     #   with:
     #     python-version: 3.7
     # - name: Install python dependencies
     #   run:  python -m pip install codemagic-cli-tools
     # - name: Initialize Keychain with certificate
     #   run: |
     #     keychain initialize
     #     keychain add-certificates --certificate ~/Library/MobileDevice/Certificates/certificate.p12 --certificate-password ${{ secrets.p12_password }}
    
     - name: 配置Flutter环境
       uses: subosito/flutter-action@v2.12.0
       # with:
       #   flutter-version: '1.12.13+hotfix.9'
       
     - name: 清理环境和安装依赖
       run: |
         flutter clean 
         flutter pub get
     
     - name: 编译生成ipa
       run: |
         flutter gen-l10n
         flutter build ipa --release --export-options-plist="ExportOptions.plist"
         find ./ -type f -name *.ipa 
         
         # xcode-project use-profiles
         # flutter build ios --release --no-codesign
         # xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --config Release
         
     # - name: 上传ios包
     #   uses: actions/upload-artifact@v4.0.0
     #   with:
     #    name: adhoc-ipa
     #    # Path to the release files
     #    path: build/ios/ipa/*.ipa
