# 部署python-demo仓库代码到开发环境
name: python-demo-dev

on:
  workflow_dispatch:
    inputs:
      var1:
        description: '测试变量'
        default: '这是测试变量的值'
        required: true
        type: string
      environment:
        description: '环境'
        required: false
        type: environment

jobs:
  build:
    name: 编译
    uses: ./.github/workflows/build_python_dev.yml
    secrets: inherit
    with:
      # 配置参数通过api动态获取
      artifact_name: python-demo-dev
      # repository: 'https://github.com/deming-org/python-demo'
      repository: 'deming-org/python-demo'
      ref: 'main'
      repo_type: 'git'
  
  deploy:
    name: 主机部署
    needs:
      - build
    uses: ./.github/workflows/deploy_dev.yml
    secrets: inherit
    with:
      # 配置参数通过api动态获取
      host_group: python-demo-dev
      deploy_path: /data/python-demo/
      setup_cmd: 'bash setup.sh'
      restart_cmd: 'bash restart.sh'
