name: 可重用工作流示例 - 私有仓库

on:
  repository_dispatch:
    types: [start-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Run job
      run: |
        pwd && ls -t1
        echo "Hello, ${{ github.event.client_payload.name }}"


