name: 可重用工作流示例 - 公共仓库

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: false

defaults:
  run:
    working-directory: ./scripts
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 打印操作
      run: |
        pwd
        echo -e "config-pat=>${{ inputs.config-path }}\ntoken=> ${{ secrets.token }}\nSSH_HOST=> ${{ secrets.SSH_HOST }}"
        echo -e "GITHUB_WORKFLOW: $GITHUB_WORKFLOW \t GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
