name: 可重用工作流示例 - 公共仓库

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: false
        
# defaults.run.working-directory无法使用变量，不满足需求
# defaults:
#   run:
#     working-directory: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 预建工作目录
      # 默认的工作目录环境变量是GITHUB_WORKSPACE对应的值
      run: mkdir -pv ${{ github.workflow }}
      
    - name: 打印操作
      working-directory: ${{ github.workflow }}
      run: |
        pwd
        echo -e "config-pat=>${{ inputs.config-path }}\ntoken=> ${{ secrets.token }}\nSSH_HOST=> ${{ secrets.SSH_HOST }}"
        echo -e "GITHUB_WORKFLOW: $GITHUB_WORKFLOW \t GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
