name: 可重用工作流示例

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 打印操作
      run: |
        echo -e "config-pat=>${{ inputs.config-path }}\ntoken=> ${{ secrets.token }}\nSSH_HOST=> ${{ secrets.SSH_HOST }}"
        echo "token=> ${{ secrets.token }}" > 1.txt && cat 1.txt
